%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Put)
%;**     Description :
%;**         Puts a new element into the buffer. 
%include Common\GeneralParameters.inc(27)
%;**         uint16_t elem%>27 - New element to be put into the buffer. 
%;**     Returns     :
%;**         uint8_t %>27 - 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
